blank_issues_enabled: true
contact_links:
  - name: Questions & Discussions ğŸ’¬
    url: https://github.com/SamErde/TheCleaners/discussions
    about: Please use GitHub discussions for any questions.
  - name: Documentation ğŸ“š
    url: https://day3bits.com/TheCleaners
    about: Documentation for the TheCleaners project.
  - name: ReadTheDocs ğŸ“– (Alternate/Backup Documentation Site)
    url: https://thecleaners.readthedocs.io/en/latest/
    about: ReadTheDocs for the TheCleaners project.
#  - name: Basic FAQs â“
#    url: https://github.com/SamErde/TheCleaners/wiki/FAQs
#    about: Answers to the Basic Frequently Asked Questions
